// Copyright 2017-2022 @polkadot/ui-assets authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/ui-assets', version: '0.87.8-7' };
