// Copyright 2017-2022 @polkadot/ui-shared authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/ui-shared', version: '0.88.1' };
