// Copyright 2017-2025 @polkadot/ui-settings authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @polkadot/dev

export const packageInfo = { name: '@polkadot/ui-settings', path: 'auto', type: 'auto', version: '3.15.3-1-x' };
